# Generated by Django 5.1 on 2024-09-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_label_name_label_label_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='label',
            new_name='name',
        ),
    ]
